name: mynextproperty
description: "A Malaysian geographic visualizer and infographic for planning your next property"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

platforms:
  android:

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.3
  url_launcher: ^6.3.1
  latlong2: ^0.10.1
  flutter_map: ^8.3.2
  equatable: ^2.0.0
  geocoding: ^5.0.0
  http: ^1.2.0
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # allow sqlite read sql scripts
  assets:
    - assets/sql/